language: python
python:
  - 2.7
  - 3.6
script: pytest
deploy:
  provider: pypi
  user: slank-pyscratch
  password:
    secure: $PYPI_PASSWORD_ENC
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  server: https://test.pypi.org/legacy